server:
  port: 80

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://172.18.204.243:3306/weipai?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: zhengxin6401808
  redis:
    database: 1
    host: 47.115.41.69
    port: 6379
    password: zhengXIN@123
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 0
    timeout: 5000s