server:
  port: 8089

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/youdi?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: root
  redis:
    database: 2
    host: 47.115.41.69
    port: 6379
    password: zhengXIN@123
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 0
    timeout: 5000s

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql语句打印到控制台的配置